---
title: " `r params$adminlevel_1` - Countdown Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
    highlight: kate
  officedown::rdocx_document:
    reference_docx: subnational-one-pager-template.docx
    page_size:
      height: 8.3
      width: 11.7
      orient: "landscape"
    page_margins:
      bottom: 0.1
      top: 0
      right: 0
      left: 0
      gutter: 0
      header: 0
      footer: 0
  pdf_document:
    toc: false
    latex_engine: lualatex
    number_sections: false
    keep_tex: true
    includes:
      in_header: |
        \usepackage[a4paper, margin=0.2in, bottom=0.1in, top=0in, right=0.2in, left=0.2in, includehead, includefoot]
        
params:
  cache: NULL
  country: NULL
  adminlevel_1: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  include = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = TRUE,
  dpi=1200
)

library(cd2030.rmncah)
library(dplyr)
library(purrr)
library(flextable)
library(reactable)
library(officedown)
library(officer)

cache <- params$cache
adminlevel_1 <- params$adminlevel_1

data <- cache$countdown_data
country <- cache$country
last_year <- max(data$year, na.rm = TRUE)
admin1_cov <- cache$calculate_coverage('adminlevel_1')
admin2_cov <- cache$calculate_coverage('district') %>% 
  filter(adminlevel_1 == !!adminlevel_1)

plot_subnational_comparison <- function(.data, indicator = c('penta3', 'instdeliveries'), denominator = c('penta1', 'anc1', 'dhis2', 'penta1derived'), last_year) {
  check_required(.data)
  indicator <- arg_match(indicator)
  indicator_col <- sym(paste0('cov_', indicator, '_', denominator))
  
  # Color palette
  category_colors <- c(
    "Lower than average" = "#145374",
    "Average" = "#45A9E3",
    "Higher than average" = "#A9DCFA"
  )
  
  df <- admin1_cov %>% 
    filter(year == last_year) %>% 
    select(adminlevel_1, !!indicator_col) %>% 
    arrange(!!indicator_col) %>% 
    mutate(
      category = case_when(
        !!indicator_col <= quantile(!!indicator_col, 0.33) ~ "Lower than average",
        !!indicator_col <= quantile(!!indicator_col, 0.66) ~ "Average",
        TRUE ~ "Higher than average"
      )
    ) 
  
  cat_positions <- df %>%
    mutate(x = as.numeric(factor(adminlevel_1, levels = adminlevel_1))) %>%
    summarise(x = mean(x), .by = category)

  df %>% 
    ggplot(aes(x = factor(adminlevel_1, levels = adminlevel_1), y = !!indicator_col, fill = category)) +
    geom_col(width = 1) +
    geom_col(
      data = filter(df, adminlevel_1 == !!adminlevel_1),
      aes(x = adminlevel_1),
      fill = "yellow", color = "black", width = 1, size = 0.5
    ) +
    geom_text(
      data = filter(df, adminlevel_1 == !!adminlevel_1),
      aes(x = adminlevel_1, y = !!indicator_col / 2, label = adminlevel_1), 
      vjust = 0.5, angle = 90, hjust = 0.5,  # Center vertically and horizontally
      fontface = "bold", color = "black",
      size = 3
    ) +
  
    geom_label(
      data = cat_positions,
      aes(x = x, y = 10, label = category),
      inherit.aes = FALSE,
      size = 3,
      fill = "white",
      color = "black",
      label.size = 0
    ) +
    
    scale_fill_manual(values = category_colors) +
    scale_y_continuous(limits = c(0, 105), expand = c(0, 0)) +
    labs(
      title = str_glue("{str_to_title(indicator)} immunization, by region, {country}, {last_year} (HMIS)"),
      x = NULL, y = NULL
    ) +
    cd_report_theme(base_size = 7) +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      legend.position = "none",
      legend.title = element_blank(),
      # legend.margin = margin(0, 0, -10, 0),
      plot.margin = margin(0, 0, 0, 0)
    )
}

get_top_bottom_table <- function(.data, indicator = c('penta3', 'instdeliveries'), denominator = c('penta1', 'anc1', 'dhis2', 'penta1derived')) {
  check_required(.data)
  indicator <- arg_match(indicator)
  denominator <- arg_match(denominator)
  
  indicator_col <- sym(paste0('cov_', indicator, '_', denominator))
  
  max_year <- max(.data$year, na.rm = TRUE)

  .data %>% 
    select(year, district, !!indicator_col) %>% 
    mutate(!!indicator_col := round(!!indicator_col)) %>% 
    filter(!is.na(!!indicator_col)) %>% 
    pivot_wider(names_from = year, values_from = !!indicator_col) %>%
    arrange(desc(!!sym(as.character(max_year)))) %>%
    mutate(rank = row_number()) %>%
    filter(rank <= 4 | rank > (n() - 4)) %>%
    select(-rank) %>%
    flextable() %>%
    set_caption(caption = str_glue("Top and bottom 4 Coverage {indicator}, by districts (HMIS)"), ) %>%
    # style(i = 1, part = "caption", pr_t = fp_text(bold = TRUE, font.size = 9)) %>%
    fontsize(part = 'body', size = 7) %>%
    bold(part = "header", bold = TRUE) %>%
    fontsize(part = 'header', size = 7) %>%
    set_table_properties(layout = "autofit")
}
```

<!---BLOCK_MULTICOL_START--->

```{r, fig.width=4, fig.height=2}

cov <- cache$calculate_indicator_coverage('district')

cov <- cov %>% 
  filter(adminlevel_1 == !!adminlevel_1, year == last_year) %>% 
  # select(district, totunder1_dhis2, totinftpenta_penta1, totinftpenta_penta1derived)
  select(district, totunder1_dhis2)

table_data <- data %>%
  filter(adminlevel_1 == !!adminlevel_1, year == last_year) %>%
  distinct(district, total_pop, live_births) %>%
  # distinct(district, total_pop) %>%
  left_join(cov, join_by(district)) %>%
  mutate(across(where(is.numeric), ~ round(.x)))

totals <- table_data %>%
  summarise(across(where(is.numeric), sum, na.rm = TRUE)) %>%
  mutate(district = !!adminlevel_1)
  
bind_rows(totals, table_data) %>% 
  relocate(district) %>% 
  flextable() %>%
  set_header_labels(
    district = "District",
    total_pop = "Population",
    live_births = "Live Births",
    totunder1_dhis2 = 'Under 1'
  ) %>%
  fontsize(part = 'body', size = 7) %>%
  bold(part = "header", bold = TRUE) %>%
  fontsize(part = 'header', size = 7) %>%
  bold(i = 1, part = "body") %>% 
  set_table_properties(layout = "autofit")
```

```{r, fig.width=4, fig.height=2}
years <- unique(data$year)

data %>%
          calculate_overall_score(cache$threshold, region = adminlevel_1) %>%
          mutate(
            type = case_when(
              no %in% c("1a", "1b", "1c") ~ '1. Completeness of monthly facility reporting (Immunization)',
              no %in% c("2a", "2b") ~ '2. Extreme outliers (Common Vaccine antigens)',
              no %in% c("3a", "3b",'3f', '3g') ~ '3. Consistency of annual reporting'
            )
          ) %>%
          as_grouped_data(groups = 'type') %>%
          as_flextable() %>%
          bold(j = 1, i = ~ !is.na(type), bold = TRUE, part = "body") %>%
          bold(part = "header", bold = TRUE) %>%
          colformat_double(i = ~ is.na(type) & !no %in% c("3a", "3b"), j = as.character(years), digits = 0, big.mark = ",") %>%
          colformat_double(i = ~ is.na(type) & no %in% c("3a", "3b"), j = as.character(years), digits = 2) %>%
          bg(
            i = ~ is.na(type) & !no %in% c("3a", "3b"),
            j = as.character(years),
            bg = function(x) {
              # Use map to apply function to each cell
              result <- map_chr(as.list(x), ~ {
                if (is.na(.x) || is.null(.x) || !is.numeric(.x)) {
                  return("transparent")
                } else if (.x >= threshold) {
                  return("seagreen")
                } else if (.x >= 41 && .x < threshold) {
                  return("yellow")
                } else if (.x <= 40) {
                  return("red")
                } else {
                  return("transparent")
                }
              })
              return(result)
            },
            part = "body"
          ) %>%
          bg(
            i = ~ !is.na(type), part = "body",
            bg = 'lightgoldenrodyellow'
          ) %>%
   fontsize(size = 9) %>% 
          theme_vanilla() %>%
  set_table_properties(layout = "autofit") %>% 
  set_caption(caption = 'Table 1: Summary reported immunization health facility data DHIS2')
```


```{r, fig.width=4, fig.height=1.5}
run_columnbreak()
admin1_cov %>% 
  filter_coverage('penta3', denominator = cache$get_denominator('penta3'), region = adminlevel_1) %>% 
  plot() +
  cd_report_theme(base_size = 7) +
  theme(
    legend.position = 'none',
    plot.margin = margin(0, 0, 0, 0)
  )
```

```{r, fig.width=4, fig.height=2.5}
plot_subnational_comparison(admin1_cov, 'penta3', denominator = cache$get_denominator('penta3'), last_year = last_year)
```


```{r, fig.width=5, fig.height=1.5}
get_top_bottom_table(admin2_cov, 'penta3', denominator = cache$get_denominator('penta3'))
```

```{r, fig.width=4, fig.height=1.5}
run_columnbreak()

admin1_cov %>% 
  filter_coverage('instdeliveries', denominator = cache$get_denominator('instdeliveries'), region = adminlevel_1) %>% 
  plot() +
  cd_report_theme(base_size = 7) +
  theme(
    legend.position = 'none',
    plot.margin = margin(0, 0, 0, 0)
  )
```

```{r, fig.width=4, fig.height=2.5}
plot_subnational_comparison(admin1_cov, 'instdeliveries', denominator = cache$get_denominator('penta3'), last_year = last_year)
```

```{r, fig.width=5, fig.height=1.5}
get_top_bottom_table(admin2_cov, 'instdeliveries', denominator = cache$get_denominator('instdeliveries'))
```

<!---BLOCK_MULTICOL_STOP{widths: [3,4,4], space: 0.2, sep: true}--->
